const AdminActionTypes = {
  SET_CURRENT_ADMIN: "SET_CURRENT_ADMIN",
  SIGN_OUT_START: "SIGN_OUT_START",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_IN_START: "SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  CHECK_ADMIN_TOKEN: "CHECK_ADMIN_TOKEN",
};
export default AdminActionTypes;
