const UsersActionTypes = {
  //GET USER
  GET_USERS: "GET_USERS",
  //SEARCH USER
  SEARCH_USER: "SEARCH_USER",
  SET_USERS: "SET_USERS",
  //DELETE USER
  CHOSEN_DELETE_USER: "CHOSEN_DELETE_USER",
  SET_DELETED_USER: "SET_DELETED_USER",
  //CREATE USER
  CREATE_USER: "CREATE_USER",
  SET_CREATED_USER: "SET_CREATED_USER",
  //MODIFY USER
  MODIFY_USER: "MODIFY_USER",
  SET_MODIFY_USER: "SET_MODIFY_USER",
  //GET, SET, CREATE GROUP
  GET_GROUP: "GET_GROUP",
  SET_GROUP: "SET_GROUP",
  CREATE_GROUP: "CREATE_GROUP",
  SET_CREATED_GROUP: "SET_CREATED_GROUP",
  //SET PRIVILEGE
  CHANGE_PRIVILEGE: "CHANGE_PRIVILEGE",
  SET_PRIVILEGE: "SET_PRIVILEGE",
};
export default UsersActionTypes;
